version: "3"

services:
  PostgresSql:
    image: postgres:13
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5000:5432
    restart: always
  redis:
    image: redis:6.2
    restart: always
    volumes:
      ./redis/data:/data
  nodejs:
    build: .
    command: node index.js
    environment:
      postgresHOST: "PostgresSql"
      redisHOST:    "redis"
      PORT: 8000
    restart: always
    depends_on:
      - PostgresSql
      - redis
  nginx:
    image: nginx:1.21
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
    volumes:
     - ./public:/usr/share/nginx/html:ro
     - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - nodejs
    restart: always